# Generated by Django 2.2.1 on 2019-05-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0002_auto_20190517_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_device', to='authapp.EndUser'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_id_log', to='deviceapp.Device'),
        ),
    ]
