# Generated by Django 2.2.1 on 2019-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0003_auto_20190518_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='avg_pres',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='avg_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='avg_voc',
            field=models.FloatField(),
        ),
    ]
