# Generated by Django 2.2.1 on 2019-10-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0004_auto_20190520_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='pushed',
            field=models.BooleanField(default=False),
        ),
    ]
