# Generated by Django 2.2.1 on 2019-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190518_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='reset_status',
            field=models.BooleanField(default=False),
        ),
    ]
